python dual_inference.py \
	-source=SpeechSplit/assets/wavs/p226/p226_003.wav \
	-target=SpeechSplit/assets/wavs/p228/p228_024.wav \
	-output_dir=Converted_wavs/ \
	-output_name=test \
	-speech_split_conf=SpeechSplit/config.json \
	-ss_g=SpeechSplit/run/models/22k_waveglow/G/180000-G.ckpt \
	-ss_p=SpeechSplit/run/models/22k_waveglow/P/160000-P.ckpt \
	-waveglow_model=Waveglow/models/waveglow_256channels_universal_v5.pt \
	-waveglow_conf=Waveglow/config.json \
	-sigma=1.0 \